### PR TITLE
[rcore][drm] Improved touch input handling and multitouch support, closes #4842

### LINKED ISSUE #4842: [rcore][drm] `GetTouchPointCount()` returns 1 when screen is not touched
Just did a git pull to get the latest; compiled on a RaspberryPi 3 with make PLATFORM=PLATFORM_DRM

To reproduce just add to the core_input_multitouch.c a statement to print tCount and compile and run it.

When touching the screen first with your index finger when with your thumb  and then releasing the index finger and after that the thumb the tCount will still show 1 even though nothing touches the screen anymore.

### PR DESCRIPTION
**Pull request by MULTidll**
**Input Handling Improvements:**

* Added new fields to the platform struct for tracking multitouch state: `mouseIsTouch`, `touchActive`, `touchPosition`, and `touchId` arrays, improving the accuracy and reliability of multitouch input.
* Refactored the evdev device configuration logic to prioritize touchscreens over mice, ensuring the correct device is selected and properly initialized. Devices are now logged with their type, and lower-priority devices are ignored. 
* Overhauled the multitouch event processing in `PollMouseEvents`: now tracks per-slot touch activity, position, and IDs, handles slot switching, and processes pressure events to detect touch lift-off. This enables robust multitouch support and corrects previous issues with touch state tracking. 
* Added initialization and reset logic for the new multitouch state fields in input setup functions.

**Bug Fixes:**

* Replaced legacy `FLAG_SET`, `FLAG_CLEAR`, and `FLAG_IS_SET` macros with direct bitwise operations for window and input flags, improving clarity and maintainability. 
* Improved framebuffer handling in `SwapScreenBuffer` by retrieving the software-rendered color buffer, checking for errors, and performing a direct copy or scaled blit as appropriate.

### CODE REVIEW

**Comment by raysan5** [comment]
@MULTidll I'm afraid you override current master branch changes, please, could you sync to latest master before adding the new changes?

 > Replaced legacy FLAG_SET, FLAG_CLEAR, and FLAG_IS_SET macros...

These is the latest approach, please, use it.

**Comment by MUL7ii** [comment]
image
@raysan5 It was synced to latest master branch before adding the new changes

File: src/platforms/rcore_drm.c [hunk 1]
```diff
@@ -220,7 +224,7 @@ static const short linuxToRaylibMap[KEYMAP_SIZE] = {
     248, 0,   0,   0,   0,   0,   0,   0,
 
     // Gamepads are mapped according to:
-    // REF: https://www.kernel.org/doc/html/next/input/gamepad.html
```
Comment (raysan5) [inline src/platforms/rcore_drm.c:223]: Changed from current master: https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_drm.c#L223

File: src/platforms/rcore_drm.c [hunk 2]
```diff
@@ -265,8 +269,6 @@ static int FindMatchingConnectorMode(const drmModeConnector *connector, const dr
 static int FindExactConnectorMode(const drmModeConnector *connector, uint width, uint height, uint fps, bool allowInterlaced);      // Search exactly matching DRM connector mode in connector's list
 static int FindNearestConnectorMode(const drmModeConnector *connector, uint width, uint height, uint fps, bool allowInterlaced);    // Search the nearest matching DRM connector mode in connector's list
 
-static void SetupFramebuffer(int width, int height); // Setup main framebuffer (required by InitPlatform())
```
Comment (raysan5) [inline src/platforms/rcore_drm.c:268]: Removed from current master branch https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_drm.c#L268

File: src/platforms/rcore_drm.c [hunk 3]
```diff
@@ -1149,7 +1165,8 @@ int InitPlatform(void)
 
     // Initialize graphic device: display/window and graphic context
     //----------------------------------------------------------------------------
-    FLAG_SET(CORE.Window.flags, FLAG_FULLSCREEN_MODE);
+    CORE.Window.fullscreen = true;
```
Comment (raysan5) [inline src/platforms/rcore_drm.c]: ` CORE.Window.fullscreen = true;` was removed in latest master branch

File: src/platforms/rcore_drm.c [hunk 4]
```diff
@@ -1298,8 +1315,8 @@ int InitPlatform(void)
         CORE.Window.screen.height = CORE.Window.display.height;
     }
 
-    const bool allowInterlaced = FLAG_IS_SET(CORE.Window.flags, FLAG_INTERLACED_HINT);
```
Comment (raysan5) [inline src/platforms/rcore_drm.c:1301]: I prefer to keep using the provided macros

File: src/platforms/rcore_drm.c [hunk 5]
```diff
@@ -1329,7 +1346,7 @@ int InitPlatform(void)
 
     TRACELOG(LOG_INFO, "DISPLAY: Selected DRM connector mode %s (%ux%u%c@%u)", platform.connector->modes[platform.modeIndex].name,
         platform.connector->modes[platform.modeIndex].hdisplay, platform.connector->modes[platform.modeIndex].vdisplay,
-        FLAG_IS_SET(platform.connector->modes[platform.modeIndex].flags, DRM_MODE_FLAG_INTERLACE)? 'i' : 'p',
```
Comment (raysan5) [inline src/platforms/rcore_drm.c:1332]: I prefer to keep using the provided macros

File: src/platforms/rcore_drm.c [hunk 6]
```diff
@@ -1562,17 +1579,17 @@ int InitPlatform(void)
...
 
-    if (FLAG_IS_SET(CORE.Window.flags, FLAG_WINDOW_MINIMIZED)) MinimizeWindow();
+    if ((CORE.Window.flags & FLAG_WINDOW_MINIMIZED) > 0) MinimizeWindow();
 
     // If graphic device is no properly initialized, we end program
     if (!CORE.Window.ready) { TRACELOG(LOG_FATAL, "PLATFORM: Failed to initialize graphic device"); return -1; }
     else SetWindowPosition(GetMonitorWidth(GetCurrentMonitor())/2 - CORE.Window.screen.width/2, GetMonitorHeight(GetCurrentMonitor())/2 - CORE.Window.screen.height/2);
 
     // Set some default window flags
-    FLAG_CLEAR(CORE.Window.flags, FLAG_WINDOW_HIDDEN);       // false
```
Comment (raysan5) [inline src/platforms/rcore_drm.c:1572]: I prefer to keep using the provided macros

File: src/platforms/rcore_drm.c [hunk 7]
```diff
@@ -1866,24 +1883,31 @@ static void ProcessKeyboard(void)
 }
 #endif  // SUPPORT_SSH_KEYBOARD_RPI
 
-// Initialize user input from evdev(/dev/input/event<N>)
+// Initialise user input from evdev(/dev/input/event<N>)
```
Comment (raysan5) [inline src/platforms/rcore_drm.c]: raylib uses `Initialize` spelling on all the modules

File: src/platforms/rcore_drm.c [hunk 8]
```diff
@@ -1866,24 +1883,31 @@ static void ProcessKeyboard(void)
...
     struct dirent *entity = NULL;
 
-    // Initialize keyboard file descriptor
+    // Initialise keyboard file descriptor
     platform.keyboardFd = -1;
     platform.mouseFd = -1;
 
     // Reset variables
-    for (int i = 0; i < MAX_TOUCH_POINTS; i++)
+    for (int i = 0; i < MAX_TOUCH_POINTS; ++i)
```
Comment (raysan5) [inline src/platforms/rcore_drm.c]: raylib uses the `i++`  for in all the modules

File: src/platforms/rcore_drm.c [hunk 9]
```diff
@@ -2276,39 +2333,97 @@ static void PollMouseEvents(void)
             if (event.code == ABS_X)
             {
                 CORE.Input.Mouse.currentPosition.x = (event.value - platform.absRange.x)*CORE.Window.screen.width/platform.absRange.width;    // Scale according to absRange
-                CORE.Input.Touch.position[0].x = (event.value - platform.absRange.x)*CORE.Window.screen.width/platform.absRange.width;        // Scale according to absRange
-
-                touchAction = 2;    // TOUCH_ACTION_MOVE
+                
+                // Update single touch position only if it's active and no MT events are being used
+                if (platform.touchActive[0] && !isMultitouch) {
```
Comment (raysan5) [inline src/platforms/rcore_drm.c]: Please, review raylib coding conventions

File: src/platforms/rcore_drm.c [hunk 10]
```diff
@@ -2276,39 +2333,97 @@ static void PollMouseEvents(void)
...
+                    platform.touchPosition[0].y = (event.value - platform.absRange.y)*CORE.Window.screen.height/platform.absRange.height;
+                    if (touchAction == -1) touchAction = 2;    // TOUCH_ACTION_MOVE
+                }
             }
 
             // Multitouch movement
-            if (event.code == ABS_MT_SLOT) platform.touchSlot = event.value;   // Remember the slot number for the folowing events
+            if (event.code == ABS_MT_SLOT) {
```
Comment (raysan5) [inline src/platforms/rcore_drm.c]: Please, review raylib coding conventions

File: src/platforms/rcore_drm.c [hunk 11]
```diff
@@ -2480,82 +2655,4 @@ static int FindNearestConnectorMode(const drmModeConnector *connector, uint widt
     return nearestIndex;
 }
 
-// Compute framebuffer size relative to screen size and display size
```
Comment (raysan5) [inline src/platforms/rcore_drm.c:2483]: This function is in raylib current master branch https://github.com/raysan5/raylib/blob/master/src/platforms/rcore_drm.c#L2485

File: src/platforms/rcore_drm.c [hunk 12]
```diff
@@ -2450,21 +2625,21 @@ static int FindNearestConnectorMode(const drmModeConnector *connector, uint widt
...
 
-        if ((FLAG_IS_SET(mode->flags, DRM_MODE_FLAG_INTERLACE) > 0) && !allowInterlaced)
+        if ((mode->flags & DRM_MODE_FLAG_INTERLACE) && !allowInterlaced)
         {
             TRACELOG(LOG_TRACE, "DISPLAY: DRM shouldn't choose an interlaced mode");
             continue;
         }
 
-        const int unusedPixels = (mode->hdisplay - width)*(mode->vdisplay - height);
+        const int unusedPixels = (mode->hdisplay - width) * (mode->vdisplay - height);
```
Comment (raysan5) [inline src/platforms/rcore_drm.c]: Please, review raylib  coding conventions

**Comment by raysan5** [comment]
@MULTidll Added multiple comments, this  PR overrides changes in current master branch, also, please review raylib coding conventions not followed by the code. Thanks.

**Comment by MUL7ii** [comment]
@raysan5 ig now it is all cleaned up

**Comment by raysan5** [comment]
@MULTidll thanks  for  the review, please note that [raylib code conventions](https://github.com/raysan5/raylib/blob/master/CONVENTIONS.md) requires aligned braces:

```c
if (condition)
{

}
```

Please, can you review it?

**Comment by MUL7ii** [comment]
@raysan5 yep sure

File: src/platforms/rcore_drm.c [hunk 13]
```diff
@@ -135,8 +135,12 @@ typedef struct {
     char currentButtonStateEvdev[MAX_MOUSE_BUTTONS]; // Holds the new mouse state for the next polling event to grab
     bool cursorRelative;                // Relative cursor mode
     int mouseFd;                        // File descriptor for the evdev mouse/touch/gestures
+    bool mouseIsTouch;                  // Check if the current mouse device is actually a touchscreen
     Rectangle absRange;                 // Range of values for absolute pointing devices (touchscreens)
     int touchSlot;                      // Hold the touch slot number of the currently being sent multitouch block
+    bool touchActive[MAX_TOUCH_POINTS]; // Track which touch points are currently active
```
Comment (raysan5) [inline src/platforms/rcore_drm.c:141]: Why are those additional variables required over the already available ones on [CORE structure](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L352)?

Comment (MUL7ii) [reply src/platforms/rcore_drm.c:141]: the mouseIsTouch track if the current mouse like device is actually a touchscreen used for device prioritization when multiple input devices exist and the touchactive to prevent ghosting

**Comment by raysan5** [comment]
@MULTidll thanks for the improvements and reviews!
